### ISSUE TITLE
hi there guys

### ISSUE THREAD

**Issue by FrankOcean11** [jorditost/BlobPersistence#1]
.

**Comment by jorditost** [comment]
Hi @FrankOcean11,

First of all, I don't really understand what are you trying to do with the sketch. Could you please be more specific?

This sketch does not store any image in your file system. The screenshot from us you are seeing is just a reference.

As you can see in the README file, the original algorithm is explained in Daniel Shiffman's blog:

http://shiffman.net/2011/04/26/opencv-matching-faces-over-time/

You will see step by step what it does. It detects when a face has entered into the camera viewport, assigns an ID to each face and follows it over time. But it doesn't stores anything. 

If you need to save a screenshot when a face is detected you should check the Processing basics for saving images. For example:

https://processing.org/reference/saveFrame_.html

If you need support while implementing your project, the Processing Forum or Stackoverflow is the place to ask. But please, before you ask anything:
1. Be sure you have tried everything and cannot do it by yourself.
2. Check how to ask for support in community forums: http://stackoverflow.com/help/how-to-ask
3. Write a detailed explanation of what are you trying to do (your algorithm) and what have you tried so far. If the community doesn't understand you, you won't receive any help!

**Comment by FrankOcean11** [comment]
im sorry perhaps i should have come out more clear as to what i was
expecting and what i wanted from the sketch, well what i wanted is to store
the photos with id to a folder in the folder of the pde file where Which
Face Is Which, that was i can start editing your code to rather then use
ID# it will use names IF the face was already saved in that folder where
all the other photos will be store for later recalling


Frank's Desig'Nature

"Designed Signature Inspired by Nature"

**Comment by FrankOcean11** [comment]
thumbs up Jordii
